 
version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu

hooks:
  ApplcationStop:
    - location: ./code_deployment_scripts/applicationStop.sh
      timeout: 800

  BeforeInstall:
    - location: ./code_deployment_scripts/beforeInstall.sh
      timeout: 300

  AfterInstall:
    - location: ./code_deployment_scripts/afterInstall.sh
      timeout: 900

  ApplicationStart:
    - location: ./code_deployment_scripts/applicationStart.sh
      timeout: 300 